version: '3.8'

services:
  app:
    container_name: laravel_docker_app
    build:
      context: .
      dockerfile: Dockerfile
    image: pangrekarsandesh/laravel-docker-app-img:latest  # Specify your custom image name
    volumes:
      - .:/var/www/html:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache/default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      SERVER_NAME: ${SERVER_NAME}

  db:
    image: mysql:8.0
    container_name: laravel_docker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER and MYSQL_PASSWORD environment variables are not required when configuring the root user.
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_docker_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 

  #node:
    #image: node:18
    #container_name: laravel_docker_nodejs
    #working_dir: /var/www/html
    #volumes:
    #  - .:/var/www/html
    #stdin_open: true
    #tty: true

volumes:
  db_data: